query($gender: Gender, $minDegree: Degree, $raceEthnicity: [String!]) {
  degreesBySchool(gender: $gender,
                  minDegree: $minDegree, 
                  raceEthnicity: $raceEthnicity) {
    type
    features {
      type
      geometry{
        type
        coordinates
      }
      properties {
        id	
        name
        degreeCount
        lon
        lat
      }
    }
  }
}