query {
  degreesBySchool {
    type
    features {
      type
      geometry{
        type
        coordinates
      }
      properties {
        id	
        name
        degreeCount
        lon
        lat
      }
    }
  }
}